function db = bioChemFluidsStructs()
% Database of biochemical reaction parameters.
%
% RETURNS:
%   db - Struct array where each element describes one metabolic
%        reaction with the following fields:
%
%   metabolicReaction  – Name (e.g., 'MethanogenicArchae')
%   rH2, rsub          – Reactant names
%   pH2O, p2           – Product names
%   gamrH2, gamrsub,
%   gampH2O, gamp2     – Stoichiometric coefficients
%   Y_H2               – Yield coefficient (cells/mol H2)
%   alphaH2, alphasub  – Half‑saturation constants (mol/mol)
%   Psigrowthmax       – Maximum growth rate (1/s)
%   bbact              – Decay rate (1/s)
%   nbactMax           – Maximum cell density (1/m³)
%   bactdiff           - microbial diffusion coefficient (m^2/s)
%   Add new reactions by appending additional struct entries following
%   the same pattern.

db = struct(...
    'metabolicReaction', 'MethanogenicArchae', ...
    'rH2',                'H2', ...
    'rsub',               'CO2', ...
    'pH2O',               'H2O', ...
    'p2',                 'C1', ...
    'gamrH2',             -4, ...
    'gamrsub',            -1, ...
    'gampH2O',             2, ...
    'gamp2',               1, ...
    'Y_H2',               3.90875e11, ...
    'alphaH2',            3.6e-7, ...
    'alphasub',           1.98e-6, ...
    'Psigrowthmax',       1.338e-4, ...
    'bbact',              2.35148e-6, ...
    'nbactMax',           1e9,...
    'bactdiff', 1.e-12);

% Example for adding a second reaction (uncomment and adjust):
% db(2) = struct(...
%     'metabolicReaction', 'SulfateReducingBacteria', ...
%     'rH2',                'H2', ...
%     'rsub',               'SO4', ...
%     'pH2O',               'H2O', ...
%     'p2',                 'H2S', ...
%     ...  % fill remaining coefficients
%     );
end