function db = bioChemFluidsStructs()
% Database of biochemical reaction parameters.
%
% RETURNS:
%   db - Struct array where each element describes one metabolic
%        reaction with the following fields:
%
%   metabolicReaction  – Name (e.g., 'MethanogenicArchae')
%   rH2, rsub          – Reactant names
%   pH2O, p2           – Product names
%   gamrH2, gamrsub,
%   gampH2O, gamp2     – Stoichiometric coefficients
%   Y_H2               – Yield coefficient (cells/mol H2)
%   alphaH2, alphasub  – Half‑saturation constants (mol/mol)
%   Psigrowthmax       – Maximum growth rate (1/s)
%   bbact              – Decay rate (1/s)
%   nbactMax           – Maximum cell density (1/m³)
%   bactdiff           - microbial diffusion coefficient (m^2/s)
%   xch_seuil          -chemotaxis
%   Add new reactions by appending additional struct entries following
%   the same pattern.

db = [...
    struct(...
    'metabolicReaction', 'MethanogenicArchae', ...
    'rH2',                'H2', ...
    'rsub',               'CO2', ...
    'pH2O',               'H2O', ...
    'p2',                 'C1', ...
    'gamrH2',             -4, ...
    'gamrsub',            -1, ...
    'gampH2O',             2, ...
    'gamp2',               1, ...
    'Y_H2',               3.90875e11, ...
    'alphaH2',            3.6e-7, ...
    'alphasub',           1.98e-6, ...
    'Psigrowthmax',       1.338e-4, ...
    'bbact',              2.35148e-6, ...
    'nbactMax',           1.0e9,...
    'xch_seuil',          1.0e-7,...
    'bactdiff', 1.0e-9),...
    struct(...
    'metabolicReaction', 'AcetogenicBacteria', ...
    'rH2',                'H2', ...
    'rsub',               'CO2', ...
    'pH2O',               'H2O', ...
    'p2',                 'Ch3COOH', ...
    'gamrH2',             -4, ...
    'gamrsub',            -2, ...
    'gampH2O',             2, ...
    'gamp2',               1, ...
    'Y_H2',               1.2e11, ...
    'alphaH2',            5.0e-6, ...
    'alphasub',           5.0e-6, ...
    'Psigrowthmax',       4.0e-5, ...
    'bbact',              1.5e-6, ...
    'nbactMax',           1.0e9,...
    'xch_seuil',          1.0e-7,...
    'bactdiff',           1.0e-12),...
    ];

    % Example for adding a second reaction (uncomment and adjust):
    % db(2) = struct(...
    %     'metabolicReaction', 'SulfateReducingBacteria', ...
    %     'rH2',                'H2', ...
    %     'rsub',               'SO4', ...
    %     'pH2O',               'H2O', ...
    %     'p2',                 'H2S', ...
    %     ...  % fill remaining coefficients
    %     );
    end